#!/usr/bin/env python3
"""
Datadog API Library for {{CLIENT_NAME}}

This library provides utilities for interacting with the Datadog API:
- Monitor management (list, tag, search, downtimes)
- Host operations (list, tag, metrics)
- Event retrieval
- Log search
- User/Role management
- Synthetics operations
- Webhook creation

Environment Variables:
  - TF_VAR_{{CLIENT_NAME_UNDERSCORE}}_api_key: Datadog API key
  - TF_VAR_{{CLIENT_NAME_UNDERSCORE}}_app_key: Datadog Application key
  - DD_API_KEY: Fallback API key
  - DD_APP_KEY: Fallback App key

Usage:
  from dd_lib import monitors, downtimes, hosts
  monitors.list_monitors()
"""

__version__ = "1.0.0"
__author__ = "Generated by org-generator"
