# Makefile for {{CLIENT_NAME}} Datadog Terraform
# Generated by org-generator plugin

.PHONY: init plan apply destroy tags validate fmt clean

# Terraform commands
init:
	terraform init

plan:
	terraform plan

apply:
	terraform apply

# Apply with auto-approve
aa:
	terraform apply -auto-approve

# Apply with auto-approve and run tagging script
tfaa:
	terraform apply -auto-approve && $(MAKE) tags

# Run tagging script to add id tags to monitors
tags:
	cd add_tags && python3 caller.py append

# Check monitors without id tags (dry run)
check-tags:
	cd add_tags && python3 caller.py check

# List all monitors
list-monitors:
	cd add_tags && python3 caller.py list

# Validate terraform configuration
validate:
	terraform validate

# Format terraform files
fmt:
	terraform fmt -recursive

# Destroy all resources
destroy:
	terraform destroy

# Clean terraform cache
clean:
	rm -rf .terraform
	rm -f .terraform.lock.hcl
	rm -f terraform.tfstate*

# Target a specific module
# Usage: make target MODULE=aws_monitors
target:
	terraform plan -target=module.$(MODULE)

# Apply a specific module
# Usage: make apply-target MODULE=aws_monitors
apply-target:
	terraform apply -target=module.$(MODULE) -auto-approve && $(MAKE) tags

# Help
help:
	@echo "Available targets:"
	@echo "  init          - Initialize terraform"
	@echo "  plan          - Plan terraform changes"
	@echo "  apply         - Apply terraform changes"
	@echo "  aa            - Apply with auto-approve"
	@echo "  tfaa          - Apply with auto-approve and run tagging"
	@echo "  tags          - Run tagging script (add id tags)"
	@echo "  check-tags    - Check monitors without id tags"
	@echo "  list-monitors - List all monitors"
	@echo "  validate      - Validate terraform config"
	@echo "  fmt           - Format terraform files"
	@echo "  destroy       - Destroy all resources"
	@echo "  clean         - Clean terraform cache"
	@echo "  target        - Plan specific module (MODULE=name)"
	@echo "  apply-target  - Apply specific module (MODULE=name)"
